### PR TITLE
Fix endpoint discovery

### PR DESCRIPTION
**Pull request by rbarry82**
The original implementation of endpoint discovery had drifted (on Juju2 and Juju3), and the required observer was not started.

Correct the library, and some error handling for data in the charm itself.

### CODE REVIEW

**Comment by i-chvets** [comment]
@rbarry82 There is a [library fetch issue in CI](https://github.com/canonical/seldon-core-operator/actions/runs/4121995401/jobs/7130899969)
Not sure how to solve it.

**Comment by rbarry82** [comment]
I guess, for one, may as well update the action to the latest version.

But I can't see the secrets for your repo to know whether `charmcraft_credentials` exists at all (or whether it's set). We have a shared secret among all of our repos, but in general, following [these docs](https://juju.is/docs/sdk/remote-env-auth) to get a token and using it as a secret will help it pass. We set the TTL to the highest possible value so it basically never expires (the default is 30 days, which is too short to be meaningful in CI).

The [docs for the action](https://github.com/canonical/charming-actions/tree/main/check-libraries) are easy enough. I'm guessing from the output (charmcraft couldn't find the token) that the secret may exist, but expired or is empty.

**Comment by i-chvets** [comment]
Check libraries and publish in CI will fail due to this PR being done from fork. Acknowledging this checks failing and merging this PR without those checks after approval.

**Review by i-chvets — APPROVED** [review]
Approved.

**Comment by i-chvets** [comment]
Acknowledging CI failing in:
- Check libraries
- Publish charm

**Pull request merged**
