### PR TITLE
Update the bug template

### PR DESCRIPTION
**Pull request by kimwnasptd**
Update the bug template, based on o11y team.

### CODE REVIEW

**Comment by i-chvets** [comment]
This issue is still in Draft.

**Review by i-chvets — APPROVED** [review]
Approved. ACK create issue to address capitalization.

**Comment by i-chvets** [comment]
@kimwnasptd I approved with ACK on follow up issue and switched this PR from Draft. However, this reporsitory requires commits to be signed. I am switching this back to Draft. We need to resolve this.

**Comment by phoevos** [comment]
@kimwnasptd, feel free to merge!

**Pull request merged**
