### PR TITLE
feat: seldon-core upgrade 1.14->1.15

### PR DESCRIPTION
**Pull request by DnPlas**
Upgrade seldon-core-operator to 1.15

Dear reviewer: this PR contains a significant amount of changes, all done by comparing the upstream project [v1.15.0 manifests](https://github.com/SeldonIO/seldon-core/tree/v1.15.0/operator/config). Such manifests were taken as they are and copied into our repository.

### CODE REVIEW

**Review by i-chvets — APPROVED** [review]
Approved.

**Review by i-chvets — DISMISSED** [review]
Approved.

**Comment by i-chvets** [comment]
There are some issues with integration tests in CI.

**Comment by DnPlas** [comment]
@i-chvets ready

**Review by i-chvets — APPROVED** [review]
Re-approved.

**Pull request merged**
